<?php 
// https://leetcode.com/problems/find-the-difference/description

// You are given two strings s and t.
// String t is generated by random shuffling string s and then add one more letter at a random position.
// Return the letter that was added to t.

class Solution {

    /**
     * @param String $s
     * @param String $t
     * @return String
     */
    function findTheDifference($s, $t) {
        $sArr = array_count_values(str_split($s));
        $tArr =  array_count_values(str_split($t));
        
        foreach($tArr as $char => $count){
            // Case one if char is not found in s array it means that is the char which is added
            // Case two: char found but the count is different
            if(!in_array($char, array_keys($sArr)) ||  $count != $sArr[$char]){
                return $char;
            }
        }
        return "";
    }
}

$sol = new Solution;
$sol->findTheDifference('abcd', 'abcde')

?>